global using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("NDepend", "ND2014:AvoidNamingTypesAndNamespacesWithTheSameIdentifier", Target = "MattEland.RoguelikeRL.Client.App", Justification = "XAML managed")]
[assembly: SuppressMessage("NDepend", "ND1901:AvoidNonReadOnlyStaticFields", Target = "MattEland.RoguelikeRL.Client.Resource+Styleable", Justification = "Autogen Code")]
[assembly: SuppressMessage("NDepend", "ND2105:TypesDeclaredInTheSameNamespaceShouldHaveTheirSourceFilesStoredInTheSameDirectory", Target = "MattEland.RoguelikeRL.Client", Justification = "MauiProgram is autogenerated")]
[assembly: SuppressMessage("NDepend", "ND1207:NonStaticClassesShouldBeInstantiatedOrTurnedToStatic", Target = "MattEland.RoguelikeRL.Client.App", Justification = "XAML managed")]
[assembly: SuppressMessage("NDepend", "ND1207:NonStaticClassesShouldBeInstantiatedOrTurnedToStatic", Target = "MattEland.RoguelikeRL.Client.MainActivity", Justification = "XAML managed")]
[assembly: SuppressMessage("NDepend", "ND1207:NonStaticClassesShouldBeInstantiatedOrTurnedToStatic", Target = "MattEland.RoguelikeRL.Client.MainApplication", Justification = "XAML managed")]
[assembly: SuppressMessage("NDepend", "ND2105:TypesDeclaredInTheSameNamespaceShouldHaveTheirSourceFilesStoredInTheSameDirectory", Target = "MattEland.RoguelikeRL.Client", Justification = "Maui Feature")] 